### ISSUE TITLE
Inconsystency between images used in different steps of the lab

### ISSUE THREAD

**Issue by rmarting** [rhcs-workshops/summit-connect-madrid-developer-hub#6]
There is a inconsystency in the images displayed along the lab related to the name of the application.

The first image showed in the creation of the application uses `summit-connect` as name of the application, when the documentation says to use name and surnames. After the creationt of the component, the rest of the images show an application called `my-quarkus-app` and some of the content refers to different names.

This misalignement can impact the reader as the content is not aligned (images versus documentation).

Solution proposed: Capture again the images using the same name (e.g.: summit-connect) to avoid misunderstanding or confussion to the reader.

**Comment by rmarting** [comment]
@davidseve @fperearodriguez IMHO, this is a _big_ issue, as the reader can't be lost at some point. I don't know who capture the images, but it should be needed to take again using the same application name.

**Comment by fperearodriguez** [comment]
I agree with you, @rmarting. The misalignment is due to the change of laboratory used because of maintenance issues, and the reader can be impacted, as you said. We'll take care of this. Thanks.

**Comment by rmarting** [comment]
Who created the previous images? Could recreate it with the right name? Should do I do it?

**Comment by davidseve** [comment]
We have updated the instructions with the right images and descriptions. If you can review it, we appreciate your help.

**Comment by rmarting** [comment]
LGTM!
