### ISSUE TITLE
Execution of multiple CI pipelines

### ISSUE THREAD

**Issue by rmarting** [rhcs-workshops/summit-connect-madrid-developer-hub#8]
The current content of the documentation says that the last commit (changing the `index.md` file) triggers the pipeline, and that it is not true. The pipeline is started 3 times, one per change applied:

* Update the Java class
* Update the Unit Test class
* Update the documentation file

So, the reader can see in the CI tab the execution in parallel of 3 pipelines ... so it could be a bit weird and produce some confusion. The content of that part should be aligned with the real behavior of the pipelines, otherwise we will get multiple questions about that behavior.

![Screenshot from 2024-09-25 22-58-51](https://github.com/user-attachments/assets/ba518554-c6ed-49a8-b0de-e0d6d61a2904)

**Comment by rmarting** [comment]
@davidseve @fperearodriguez Ideas?¿

**Comment by alcivantos** [comment]
@rmarting Can we add that three pipelines are going to be triggered but the status it's not going to be succeeded until the final change in the index.md file is done? Because when we do a change in the java class, it's obvious that this pipeline is going to fail because the test for the method is not changed yet

**Comment by rmarting** [comment]
I would like to double check again, as I can't remember if the unit testing step is executed. In that case, then you are right, the first pipeline execution will fail, but the second and onwards will run successfully, once the unit test is updated. It is a behavior that we should keep in mind, or just add some comments to the reader to clarify what it is happening when the reader goes to the CI tab.

**Comment by davidseve** [comment]
Let`s put in the documentation to only make the changes in the documentation. It will be easier and we will have only one execution of the pipeline

**Comment by rmarting** [comment]
@davidseve If we do it, then many other places must be updated too, e.g: the verification of the application checks the new results from the `/hello` endpoint. I think, we can just add in the documentation that each change is triggering the pipeline, but the latest one will deploy successfully the application. The pipeline does not consume so many time, and all the executions are in parallel.

The content of the CI verification must be reviewed completely, as describes security and testing steps not included in the RHDH demo workshop. My proposal is to describe the 3 pipelines in that section, the reason of the first fail and the right execution the rest of them.

My PR #7 includes those changes and comments. Take a look!

My 2 cents.

**Comment by davidseve** [comment]
I see your point. I will do your approach, and see how it works with the 3 pipelines. Another option is to document the creation of a new branch, make the 3 commits in the new branch, create a pull request, and accept it. The user must execute more steps, but we will see only 1 pipeline.

**Comment by rmarting** [comment]
Could do it in 5 minutes everything? It it fits it, then it is a good point and aligned with a real scenario.

**Comment by davidseve** [comment]
@rmarting we did a dry run this morning. We saw that we must reduce the demo because of the time consuming. We are going to just change the documentation so the user only has to do one commit. We have updated the instructions with the right images and descriptions. If you can review it, we appreciate your help.

**Comment by rmarting** [comment]
LGTM! I repeaed the lab and now looks great.

I proposed a minor #14 PR for the introduction ... but from my point of view, the lab is perfect!!! Well done!

**Comment by davidseve** [comment]
Merged, thanks!
