### ISSUE TITLE
Which Demo system is used for this lab?

### ISSUE THREAD

**Issue by rmarting** [rhcs-workshops/summit-connect-madrid-developer-hub#9]
Checking the images of the application dashboard and the different demo platforms, it is not clear which one is the base to run this lab, as the Trusted Software Suply Chain steps are included in the documentation.

It should be a good idea add a link in the `README.md` file to link to the right item of the catalog of the Demo System to follow up this site.

**Comment by rmarting** [comment]
@davidseve @fperearodriguez Could you fix it?

**Comment by davidseve** [comment]
The right demo is: https://demo.redhat.com/catalog?item=babylon-catalog-prod%2Fenterprise.red-hat-developer-hub-demo.prod
I have updated the readme.md
